apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun
handler: crun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - name: demo-container
        image: secondstate/mysql-binlog-kafka
        env:
        - name: SQL_USERNAME
          value: root
        - name: SQL_PASSWORD
          value: password
        - name: SQL_PORT
          value: "3306"
        - name: SQL_HOSTNAME
          value: 127.0.0.1
        - name: SQL_DATABASE
          value: mysql
        - name: KAFKA_URL
          value: 127.0.0.1:9092
        - name: SLEEP_TIME
          value: "10000"
        - name: RUST_BACKTRACE
          value: full
      runtimeClassName: crun
