apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kwasm
  region: ap-northeast-1
  version: "1.26"

managedNodeGroups:
  - name: ng-kwasm
    instanceType: t3.medium
    ami: ami-0ce575f5f4db5d208
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 2
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh kwasm --container-runtime containerd
