apiVersion: batch/v1
kind: Job
metadata:
  name: insert
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: insert
        image: dm4tw/mysql-binlog-kafka-cli
        imagePullPolicy: Always
        command: ["/root/.wasmedge/bin/wasmedge", "--env", "DATABASE_URL=mysql://root:password@mysql:3306/mysql", "/insert.wasm"]
  backoffLimit: 1
