apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:11.0
        args:
        - "--server-id=1"
        - "--log-bin=mysql-bin"
        - "--max-binlog-size=4096"
        - "--binlog-format=MIXED"
        - "--sync-binlog=1"
        - "--log-slave-updates=ON"
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
        - "--max-connections=1000"
        - "--read-only=OFF"
        - "--binlog-rows-query-log-events=ON"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
